# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fct_gererTicket.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fct_gererTicket(object):
    def setupUi(self, fct_gererTicket):
        fct_gererTicket.setObjectName("fct_gererTicket")
        fct_gererTicket.resize(572, 602)
        self.verticalLayout = QtWidgets.QVBoxLayout(fct_gererTicket)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_gererTicket_enonce = QtWidgets.QLabel(fct_gererTicket)
        self.label_gererTicket_enonce.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gererTicket_enonce.setWordWrap(True)
        self.label_gererTicket_enonce.setObjectName("label_gererTicket_enonce")
        self.verticalLayout.addWidget(self.label_gererTicket_enonce)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(fct_gererTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_gererTicket_spectacle = QtWidgets.QComboBox(fct_gererTicket)
        self.comboBox_gererTicket_spectacle.setObjectName("comboBox_gererTicket_spectacle")
        self.horizontalLayout.addWidget(self.comboBox_gererTicket_spectacle)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(fct_gererTicket)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_gererTicket_representation = QtWidgets.QComboBox(fct_gererTicket)
        self.comboBox_gererTicket_representation.setObjectName("comboBox_gererTicket_representation")
        self.horizontalLayout_2.addWidget(self.comboBox_gererTicket_representation)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(fct_gererTicket)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_gererTicket_rang = QtWidgets.QComboBox(fct_gererTicket)
        self.comboBox_gererTicket_rang.setObjectName("comboBox_gererTicket_rang")
        self.horizontalLayout_3.addWidget(self.comboBox_gererTicket_rang)
        self.label_4 = QtWidgets.QLabel(fct_gererTicket)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_gererTicket_place = QtWidgets.QComboBox(fct_gererTicket)
        self.comboBox_gererTicket_place.setObjectName("comboBox_gererTicket_place")
        self.horizontalLayout_3.addWidget(self.comboBox_gererTicket_place)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.button_gererTicket = QtWidgets.QPushButton(fct_gererTicket)
        self.button_gererTicket.setStyleSheet("background-color : lineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.button_gererTicket.setObjectName("button_gererTicket")
        self.verticalLayout.addWidget(self.button_gererTicket, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(fct_gererTicket)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_prixTotal = QtWidgets.QLabel(fct_gererTicket)
        self.label_prixTotal.setObjectName("label_prixTotal")
        self.horizontalLayout_4.addWidget(self.label_prixTotal)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.table_fct_gererTicket = QtWidgets.QTableWidget(fct_gererTicket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_fct_gererTicket.sizePolicy().hasHeightForWidth())
        self.table_fct_gererTicket.setSizePolicy(sizePolicy)
        self.table_fct_gererTicket.setAutoScroll(True)
        self.table_fct_gererTicket.setObjectName("table_fct_gererTicket")
        self.table_fct_gererTicket.setColumnCount(5)
        self.table_fct_gererTicket.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererTicket.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererTicket.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererTicket.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererTicket.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererTicket.setHorizontalHeaderItem(4, item)
        self.table_fct_gererTicket.horizontalHeader().setVisible(True)
        self.table_fct_gererTicket.horizontalHeader().setCascadingSectionResizes(False)
        self.table_fct_gererTicket.horizontalHeader().setDefaultSectionSize(80)
        self.table_fct_gererTicket.horizontalHeader().setHighlightSections(True)
        self.table_fct_gererTicket.horizontalHeader().setMinimumSectionSize(80)
        self.table_fct_gererTicket.horizontalHeader().setSortIndicatorShown(False)
        self.table_fct_gererTicket.horizontalHeader().setStretchLastSection(True)
        self.table_fct_gererTicket.verticalHeader().setVisible(False)
        self.table_fct_gererTicket.verticalHeader().setCascadingSectionResizes(False)
        self.table_fct_gererTicket.verticalHeader().setSortIndicatorShown(False)
        self.table_fct_gererTicket.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table_fct_gererTicket)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(fct_gererTicket)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(fct_gererTicket)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_gererTicket_res = QtWidgets.QLabel(fct_gererTicket)
        self.label_gererTicket_res.setStyleSheet("color:rgb(245, 121, 0)")
        self.label_gererTicket_res.setText("")
        self.label_gererTicket_res.setObjectName("label_gererTicket_res")
        self.verticalLayout.addWidget(self.label_gererTicket_res)

        self.retranslateUi(fct_gererTicket)
        self.comboBox_gererTicket_spectacle.currentIndexChanged['QString'].connect(fct_gererTicket.genererRepresentation)
        self.comboBox_gererTicket_representation.currentIndexChanged['int'].connect(fct_gererTicket.genererNumRang)
        self.comboBox_gererTicket_rang.currentIndexChanged['int'].connect(fct_gererTicket.genererNumPlace)
        self.button_gererTicket.clicked.connect(fct_gererTicket.ajouterPlace)
        self.pushButton_2.clicked.connect(fct_gererTicket.annulerPanier)
        self.pushButton.clicked.connect(fct_gererTicket.validerPanier)
        QtCore.QMetaObject.connectSlotsByName(fct_gererTicket)

    def retranslateUi(self, fct_gererTicket):
        _translate = QtCore.QCoreApplication.translate
        fct_gererTicket.setWindowTitle(_translate("fct_gererTicket", "Gestion achat tickets"))
        self.label_gererTicket_enonce.setText(_translate("fct_gererTicket", "Vous pouvez gérer les tickets depuis ce menu."))
        self.label.setText(_translate("fct_gererTicket", "Spectacle:"))
        self.label_3.setText(_translate("fct_gererTicket", "Représentation: "))
        self.label_2.setText(_translate("fct_gererTicket", "No° rang:"))
        self.label_4.setText(_translate("fct_gererTicket", "No° place:"))
        self.button_gererTicket.setText(_translate("fct_gererTicket", "Ajouter Place"))
        self.label_6.setText(_translate("fct_gererTicket", "Le panier"))
        self.label_prixTotal.setText(_translate("fct_gererTicket", "Prix total:"))
        self.table_fct_gererTicket.setSortingEnabled(False)
        item = self.table_fct_gererTicket.horizontalHeaderItem(0)
        item.setText(_translate("fct_gererTicket", "nomSpec"))
        item = self.table_fct_gererTicket.horizontalHeaderItem(1)
        item.setText(_translate("fct_gererTicket", "dateRep"))
        item = self.table_fct_gererTicket.horizontalHeaderItem(2)
        item.setText(_translate("fct_gererTicket", "noRang"))
        item = self.table_fct_gererTicket.horizontalHeaderItem(3)
        item.setText(_translate("fct_gererTicket", "noPlace"))
        item = self.table_fct_gererTicket.horizontalHeaderItem(4)
        item.setText(_translate("fct_gererTicket", "Prix"))
        self.pushButton_2.setText(_translate("fct_gererTicket", "Annuler achat"))
        self.pushButton.setText(_translate("fct_gererTicket", "Valider achat"))

