# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fct_gererRepresentation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fct_gererRepresentation(object):
    def setupUi(self, fct_gererRepresentation):
        fct_gererRepresentation.setObjectName("fct_gererRepresentation")
        fct_gererRepresentation.resize(561, 602)
        self.verticalLayout = QtWidgets.QVBoxLayout(fct_gererRepresentation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fctRepresentation_enonce = QtWidgets.QLabel(fct_gererRepresentation)
        self.label_fctRepresentation_enonce.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fctRepresentation_enonce.setWordWrap(True)
        self.label_fctRepresentation_enonce.setObjectName("label_fctRepresentation_enonce")
        self.verticalLayout.addWidget(self.label_fctRepresentation_enonce)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(fct_gererRepresentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_gererRepresentation = QtWidgets.QComboBox(fct_gererRepresentation)
        self.comboBox_gererRepresentation.setObjectName("comboBox_gererRepresentation")
        self.horizontalLayout.addWidget(self.comboBox_gererRepresentation)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(fct_gererRepresentation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dateTimeEdit_gererRepresentation = QtWidgets.QDateTimeEdit(fct_gererRepresentation)
        self.dateTimeEdit_gererRepresentation.setObjectName("dateTimeEdit_gererRepresentation")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_gererRepresentation)
        self.button_ajouterRepresentaion = QtWidgets.QPushButton(fct_gererRepresentation)
        self.button_ajouterRepresentaion.setObjectName("button_ajouterRepresentaion")
        self.horizontalLayout_4.addWidget(self.button_ajouterRepresentaion)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(fct_gererRepresentation)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_2_gererRepresentation = QtWidgets.QComboBox(fct_gererRepresentation)
        self.comboBox_2_gererRepresentation.setObjectName("comboBox_2_gererRepresentation")
        self.horizontalLayout_2.addWidget(self.comboBox_2_gererRepresentation)
        self.button_supprimerRepresentaion = QtWidgets.QPushButton(fct_gererRepresentation)
        self.button_supprimerRepresentaion.setObjectName("button_supprimerRepresentaion")
        self.horizontalLayout_2.addWidget(self.button_supprimerRepresentaion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(fct_gererRepresentation)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_gererRepresentation_modification = QtWidgets.QComboBox(fct_gererRepresentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_gererRepresentation_modification.sizePolicy().hasHeightForWidth())
        self.comboBox_gererRepresentation_modification.setSizePolicy(sizePolicy)
        self.comboBox_gererRepresentation_modification.setObjectName("comboBox_gererRepresentation_modification")
        self.horizontalLayout_3.addWidget(self.comboBox_gererRepresentation_modification)
        self.dateTimeEdit_gererRepresentation_modification = QtWidgets.QDateTimeEdit(fct_gererRepresentation)
        self.dateTimeEdit_gererRepresentation_modification.setObjectName("dateTimeEdit_gererRepresentation_modification")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_gererRepresentation_modification)
        self.button_modifierRepresentation = QtWidgets.QPushButton(fct_gererRepresentation)
        self.button_modifierRepresentation.setObjectName("button_modifierRepresentation")
        self.horizontalLayout_3.addWidget(self.button_modifierRepresentation)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_fct_gererRepresentation = QtWidgets.QTableWidget(fct_gererRepresentation)
        self.table_fct_gererRepresentation.setObjectName("table_fct_gererRepresentation")
        self.table_fct_gererRepresentation.setColumnCount(2)
        self.table_fct_gererRepresentation.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererRepresentation.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_gererRepresentation.setHorizontalHeaderItem(1, item)
        self.table_fct_gererRepresentation.horizontalHeader().setVisible(True)
        self.table_fct_gererRepresentation.horizontalHeader().setCascadingSectionResizes(False)
        self.table_fct_gererRepresentation.horizontalHeader().setDefaultSectionSize(150)
        self.table_fct_gererRepresentation.horizontalHeader().setHighlightSections(True)
        self.table_fct_gererRepresentation.horizontalHeader().setMinimumSectionSize(50)
        self.table_fct_gererRepresentation.horizontalHeader().setSortIndicatorShown(False)
        self.table_fct_gererRepresentation.horizontalHeader().setStretchLastSection(True)
        self.table_fct_gererRepresentation.verticalHeader().setVisible(False)
        self.table_fct_gererRepresentation.verticalHeader().setCascadingSectionResizes(False)
        self.table_fct_gererRepresentation.verticalHeader().setSortIndicatorShown(False)
        self.table_fct_gererRepresentation.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table_fct_gererRepresentation)
        self.label_gererRepresentation_ticket = QtWidgets.QLabel(fct_gererRepresentation)
        self.label_gererRepresentation_ticket.setStyleSheet("color:rgb(245, 121, 0)")
        self.label_gererRepresentation_ticket.setText("")
        self.label_gererRepresentation_ticket.setObjectName("label_gererRepresentation_ticket")
        self.verticalLayout.addWidget(self.label_gererRepresentation_ticket)
        self.label_gererRepresentation_res = QtWidgets.QLabel(fct_gererRepresentation)
        self.label_gererRepresentation_res.setText("")
        self.label_gererRepresentation_res.setObjectName("label_gererRepresentation_res")
        self.verticalLayout.addWidget(self.label_gererRepresentation_res)

        self.retranslateUi(fct_gererRepresentation)
        self.button_ajouterRepresentaion.clicked.connect(fct_gererRepresentation.AjouterRepresentation)
        self.button_supprimerRepresentaion.clicked.connect(fct_gererRepresentation.SupprimerRepresentation)
        self.comboBox_gererRepresentation.currentIndexChanged['QString'].connect(fct_gererRepresentation.refreshResult)
        self.comboBox_2_gererRepresentation.currentIndexChanged['int'].connect(fct_gererRepresentation.NombreTicketSupprimer)
        self.comboBox_gererRepresentation_modification.currentIndexChanged['int'].connect(fct_gererRepresentation.NombreTicketModifier)
        self.button_modifierRepresentation.clicked.connect(fct_gererRepresentation.ModifierRepresentation)
        QtCore.QMetaObject.connectSlotsByName(fct_gererRepresentation)

    def retranslateUi(self, fct_gererRepresentation):
        _translate = QtCore.QCoreApplication.translate
        fct_gererRepresentation.setWindowTitle(_translate("fct_gererRepresentation", "Gestion représentation"))
        self.label_fctRepresentation_enonce.setText(_translate("fct_gererRepresentation", "Vous pouvez ajouter/supprimer/modifier des représentations pour le spectacle sélectionné."))
        self.label.setText(_translate("fct_gererRepresentation", "Spectacle:"))
        self.label_4.setText(_translate("fct_gererRepresentation", "Représentation à ajouter:"))
        self.button_ajouterRepresentaion.setText(_translate("fct_gererRepresentation", "Ajouter"))
        self.label_3.setText(_translate("fct_gererRepresentation", "Représentation à supprimer: "))
        self.button_supprimerRepresentaion.setText(_translate("fct_gererRepresentation", "Supprimer"))
        self.label_2.setText(_translate("fct_gererRepresentation", "Modification: "))
        self.button_modifierRepresentation.setText(_translate("fct_gererRepresentation", "Modifier"))
        self.table_fct_gererRepresentation.setSortingEnabled(False)
        item = self.table_fct_gererRepresentation.horizontalHeaderItem(0)
        item.setText(_translate("fct_gererRepresentation", "dateRep"))
        item = self.table_fct_gererRepresentation.horizontalHeaderItem(1)
        item.setText(_translate("fct_gererRepresentation", "nomSpec"))

