# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablesData.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tablesData(object):
    def setupUi(self, tablesData):
        tablesData.setObjectName("tablesData")
        tablesData.resize(982, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tablesData.sizePolicy().hasHeightForWidth())
        tablesData.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(tablesData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(tablesData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tabSpectacles = QtWidgets.QWidget()
        self.tabSpectacles.setObjectName("tabSpectacles")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabSpectacles)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableSpectacles = QtWidgets.QTableWidget(self.tabSpectacles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableSpectacles.sizePolicy().hasHeightForWidth())
        self.tableSpectacles.setSizePolicy(sizePolicy)
        self.tableSpectacles.setMinimumSize(QtCore.QSize(0, 400))
        self.tableSpectacles.setBaseSize(QtCore.QSize(0, 0))
        self.tableSpectacles.setColumnCount(2)
        self.tableSpectacles.setObjectName("tableSpectacles")
        self.tableSpectacles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSpectacles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSpectacles.setHorizontalHeaderItem(1, item)
        self.tableSpectacles.horizontalHeader().setDefaultSectionSize(200)
        self.tableSpectacles.horizontalHeader().setMinimumSectionSize(50)
        self.tableSpectacles.horizontalHeader().setStretchLastSection(True)
        self.tableSpectacles.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableSpectacles)
        self.label_spectacles = QtWidgets.QLabel(self.tabSpectacles)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_spectacles.setPalette(palette)
        self.label_spectacles.setText("")
        self.label_spectacles.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spectacles.setObjectName("label_spectacles")
        self.verticalLayout_3.addWidget(self.label_spectacles)
        self.tabWidget.addTab(self.tabSpectacles, "")
        self.tabRepresentations = QtWidgets.QWidget()
        self.tabRepresentations.setObjectName("tabRepresentations")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabRepresentations)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableRepresentations = QtWidgets.QTableWidget(self.tabRepresentations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableRepresentations.sizePolicy().hasHeightForWidth())
        self.tableRepresentations.setSizePolicy(sizePolicy)
        self.tableRepresentations.setMinimumSize(QtCore.QSize(0, 400))
        self.tableRepresentations.setBaseSize(QtCore.QSize(0, 0))
        self.tableRepresentations.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableRepresentations.setColumnCount(2)
        self.tableRepresentations.setObjectName("tableRepresentations")
        self.tableRepresentations.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRepresentations.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRepresentations.setHorizontalHeaderItem(1, item)
        self.tableRepresentations.horizontalHeader().setCascadingSectionResizes(True)
        self.tableRepresentations.horizontalHeader().setDefaultSectionSize(250)
        self.tableRepresentations.horizontalHeader().setHighlightSections(True)
        self.tableRepresentations.horizontalHeader().setMinimumSectionSize(50)
        self.tableRepresentations.horizontalHeader().setStretchLastSection(True)
        self.tableRepresentations.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableRepresentations)
        self.label_representations = QtWidgets.QLabel(self.tabRepresentations)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_representations.setPalette(palette)
        self.label_representations.setText("")
        self.label_representations.setAlignment(QtCore.Qt.AlignCenter)
        self.label_representations.setObjectName("label_representations")
        self.verticalLayout_2.addWidget(self.label_representations)
        self.tabWidget.addTab(self.tabRepresentations, "")
        self.tabZones = QtWidgets.QWidget()
        self.tabZones.setObjectName("tabZones")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabZones)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableZones = QtWidgets.QTableWidget(self.tabZones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableZones.sizePolicy().hasHeightForWidth())
        self.tableZones.setSizePolicy(sizePolicy)
        self.tableZones.setMinimumSize(QtCore.QSize(0, 400))
        self.tableZones.setBaseSize(QtCore.QSize(0, 0))
        self.tableZones.setColumnCount(3)
        self.tableZones.setObjectName("tableZones")
        self.tableZones.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(2, item)
        self.tableZones.horizontalHeader().setDefaultSectionSize(200)
        self.tableZones.horizontalHeader().setMinimumSectionSize(50)
        self.tableZones.horizontalHeader().setStretchLastSection(True)
        self.tableZones.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableZones)
        self.label_zones = QtWidgets.QLabel(self.tabZones)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_zones.setPalette(palette)
        self.label_zones.setText("")
        self.label_zones.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zones.setObjectName("label_zones")
        self.verticalLayout_4.addWidget(self.label_zones)
        self.tabWidget.addTab(self.tabZones, "")
        self.tabPlaces = QtWidgets.QWidget()
        self.tabPlaces.setObjectName("tabPlaces")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabPlaces)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tablePlaces = QtWidgets.QTableWidget(self.tabPlaces)
        self.tablePlaces.setObjectName("tablePlaces")
        self.tablePlaces.setColumnCount(3)
        self.tablePlaces.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlaces.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlaces.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlaces.setHorizontalHeaderItem(2, item)
        self.tablePlaces.horizontalHeader().setDefaultSectionSize(200)
        self.tablePlaces.horizontalHeader().setMinimumSectionSize(50)
        self.tablePlaces.horizontalHeader().setStretchLastSection(True)
        self.tablePlaces.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tablePlaces)
        self.label_places = QtWidgets.QLabel(self.tabPlaces)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_places.setPalette(palette)
        self.label_places.setText("")
        self.label_places.setAlignment(QtCore.Qt.AlignCenter)
        self.label_places.setObjectName("label_places")
        self.verticalLayout_5.addWidget(self.label_places)
        self.tabWidget.addTab(self.tabPlaces, "")
        self.tabDossiers = QtWidgets.QWidget()
        self.tabDossiers.setObjectName("tabDossiers")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabDossiers)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableDossiers = QtWidgets.QTableWidget(self.tabDossiers)
        self.tableDossiers.setObjectName("tableDossiers")
        self.tableDossiers.setColumnCount(1)
        self.tableDossiers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDossiers.setHorizontalHeaderItem(0, item)
        self.tableDossiers.horizontalHeader().setDefaultSectionSize(200)
        self.tableDossiers.horizontalHeader().setMinimumSectionSize(50)
        self.tableDossiers.horizontalHeader().setStretchLastSection(True)
        self.tableDossiers.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tableDossiers)
        self.label_dossiers = QtWidgets.QLabel(self.tabDossiers)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_dossiers.setPalette(palette)
        self.label_dossiers.setText("")
        self.label_dossiers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dossiers.setObjectName("label_dossiers")
        self.verticalLayout_6.addWidget(self.label_dossiers)
        self.tabWidget.addTab(self.tabDossiers, "")
        self.tabTickets = QtWidgets.QWidget()
        self.tabTickets.setObjectName("tabTickets")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabTickets)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableTickets = QtWidgets.QTableWidget(self.tabTickets)
        self.tableTickets.setObjectName("tableTickets")
        self.tableTickets.setColumnCount(6)
        self.tableTickets.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTickets.setHorizontalHeaderItem(5, item)
        self.tableTickets.horizontalHeader().setDefaultSectionSize(110)
        self.tableTickets.horizontalHeader().setMinimumSectionSize(50)
        self.tableTickets.horizontalHeader().setStretchLastSection(True)
        self.tableTickets.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tableTickets)
        self.label_tickets = QtWidgets.QLabel(self.tabTickets)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_tickets.setPalette(palette)
        self.label_tickets.setText("")
        self.label_tickets.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets.setObjectName("label_tickets")
        self.verticalLayout_7.addWidget(self.label_tickets)
        self.tabWidget.addTab(self.tabTickets, "")
        self.vueLesDossiers = QtWidgets.QWidget()
        self.vueLesDossiers.setObjectName("vueLesDossiers")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.vueLesDossiers)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableVueLesDossiers = QtWidgets.QTableWidget(self.vueLesDossiers)
        self.tableVueLesDossiers.setObjectName("tableVueLesDossiers")
        self.tableVueLesDossiers.setColumnCount(2)
        self.tableVueLesDossiers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableVueLesDossiers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVueLesDossiers.setHorizontalHeaderItem(1, item)
        self.tableVueLesDossiers.horizontalHeader().setDefaultSectionSize(110)
        self.tableVueLesDossiers.horizontalHeader().setMinimumSectionSize(50)
        self.tableVueLesDossiers.horizontalHeader().setStretchLastSection(True)
        self.tableVueLesDossiers.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.tableVueLesDossiers)
        self.label_vueDossier = QtWidgets.QLabel(self.vueLesDossiers)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_vueDossier.setPalette(palette)
        self.label_vueDossier.setText("")
        self.label_vueDossier.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vueDossier.setObjectName("label_vueDossier")
        self.verticalLayout_8.addWidget(self.label_vueDossier)
        self.tabWidget.addTab(self.vueLesDossiers, "")
        self.VueLesRepresentations = QtWidgets.QWidget()
        self.VueLesRepresentations.setObjectName("VueLesRepresentations")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.VueLesRepresentations)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableVueLesRepresentations = QtWidgets.QTableWidget(self.VueLesRepresentations)
        self.tableVueLesRepresentations.setObjectName("tableVueLesRepresentations")
        self.tableVueLesRepresentations.setColumnCount(3)
        self.tableVueLesRepresentations.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableVueLesRepresentations.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVueLesRepresentations.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVueLesRepresentations.setHorizontalHeaderItem(2, item)
        self.tableVueLesRepresentations.horizontalHeader().setDefaultSectionSize(110)
        self.tableVueLesRepresentations.horizontalHeader().setMinimumSectionSize(50)
        self.tableVueLesRepresentations.horizontalHeader().setStretchLastSection(True)
        self.tableVueLesRepresentations.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tableVueLesRepresentations)
        self.label_vueLesRepresentations = QtWidgets.QLabel(self.VueLesRepresentations)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_vueLesRepresentations.setPalette(palette)
        self.label_vueLesRepresentations.setText("")
        self.label_vueLesRepresentations.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vueLesRepresentations.setObjectName("label_vueLesRepresentations")
        self.verticalLayout_9.addWidget(self.label_vueLesRepresentations)
        self.tabWidget.addTab(self.VueLesRepresentations, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(tablesData)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(tablesData)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(tablesData.close)
        QtCore.QMetaObject.connectSlotsByName(tablesData)

    def retranslateUi(self, tablesData):
        _translate = QtCore.QCoreApplication.translate
        tablesData.setWindowTitle(_translate("tablesData", "BD Théâtre"))
        self.tabWidget.setToolTip(_translate("tablesData", "<html><head/><body><p><br/></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("tablesData", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableSpectacles.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noSpec"))
        item = self.tableSpectacles.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "nomSpec"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectacles), _translate("tablesData", "LesSpectacles"))
        item = self.tableRepresentations.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noSpec"))
        item = self.tableRepresentations.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "dateRep"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRepresentations), _translate("tablesData", "LesRepresentations"))
        item = self.tableZones.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noZone"))
        item = self.tableZones.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "catZone"))
        item = self.tableZones.horizontalHeaderItem(2)
        item.setText(_translate("tablesData", "prixZone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabZones), _translate("tablesData", "LesZones"))
        item = self.tablePlaces.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noPlace"))
        item = self.tablePlaces.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "noRang"))
        item = self.tablePlaces.horizontalHeaderItem(2)
        item.setText(_translate("tablesData", "noZone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlaces), _translate("tablesData", "LesPlaces"))
        item = self.tableDossiers.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noDos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDossiers), _translate("tablesData", "LesDossiers"))
        item = self.tableTickets.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noSpec"))
        item = self.tableTickets.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "dateRep"))
        item = self.tableTickets.horizontalHeaderItem(2)
        item.setText(_translate("tablesData", "noPlace"))
        item = self.tableTickets.horizontalHeaderItem(3)
        item.setText(_translate("tablesData", "noRang"))
        item = self.tableTickets.horizontalHeaderItem(4)
        item.setText(_translate("tablesData", "dateEmTick"))
        item = self.tableTickets.horizontalHeaderItem(5)
        item.setText(_translate("tablesData", "noDos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTickets), _translate("tablesData", "LesTickets"))
        item = self.tableVueLesDossiers.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noDos"))
        item = self.tableVueLesDossiers.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "Montant"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vueLesDossiers), _translate("tablesData", "VueLesDossiers"))
        item = self.tableVueLesRepresentations.horizontalHeaderItem(0)
        item.setText(_translate("tablesData", "noSpec"))
        item = self.tableVueLesRepresentations.horizontalHeaderItem(1)
        item.setText(_translate("tablesData", "dateRep"))
        item = self.tableVueLesRepresentations.horizontalHeaderItem(2)
        item.setText(_translate("tablesData", "nbPlaces"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VueLesRepresentations), _translate("tablesData", "VueLesReprésentations"))
        self.pushButton.setText(_translate("tablesData", "Fermer"))

